# Generated by Django 4.1.5 on 2023-01-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
