# Generated by Django 4.1.5 on 2023-01-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='duration',
        ),
    ]
